<!-- Copyright 2026 Shanghai Rujing Zhihua Information Technology Co., Ltd. -->
<script setup>
import { onMounted,ref } from 'vue'; import { api } from '../api/ehr'; import { useAuthStore } from '../stores/auth'
const auth=useAuthStore(),dashboard=ref({activeEmployees:0,pendingLeaves:0,openJobs:0,interviewingCandidates:0})
onMounted(async()=>dashboard.value=await api.dashboard())
const apps=[['员工花名册','friends-o','/employees'],['考勤打卡','clock-o','/attendance'],['请假审批','records-o','/leave'],['薪资记录','balance-list-o','/payroll'],['招聘管理','bag-o','/recruitment']]
</script>
<template><div class="page safe-top"><section class="hero brand-gradient"><div><div class="hello">你好，{{auth.user?.fullName}}</div><div class="muted-light">{{auth.user?.employeeNo}} · {{auth.user?.departmentName}} · {{auth.user?.position}}</div></div><van-icon name="setting-o" size="24"/></section><section class="card stats"><div class="stat-row four"><div><div class="stat-value">{{dashboard.activeEmployees}}</div><div class="stat-label">在职员工</div></div><div><div class="stat-value">{{dashboard.pendingLeaves}}</div><div class="stat-label">待审批</div></div><div><div class="stat-value">{{dashboard.openJobs}}</div><div class="stat-label">在招职位</div></div><div><div class="stat-value">{{dashboard.interviewingCandidates}}</div><div class="stat-label">面试中</div></div></div></section><h2 class="section-title">人事服务</h2><section class="app-grid"><router-link v-for="app in apps" :key="app[0]" :to="app[2]" class="app-icon"><span class="circle"><van-icon :name="app[1]"/></span><span>{{app[0]}}</span></router-link></section><h2 class="section-title">今日状态</h2><section class="card today"><div><b>{{dashboard.checkedIn?'已完成上班签到':'尚未签到'}}</b><p class="muted">{{dashboard.checkedOut?'今日考勤已完成':'记得按时完成上下班打卡'}}</p></div><router-link to="/attendance">去打卡</router-link></section></div></template>
<style scoped>.hero{height:138px;border-radius:22px;padding:26px 22px;display:flex;justify-content:space-between;align-items:flex-start}.hello{font-size:23px;font-weight:750;margin-bottom:8px}.muted-light{opacity:.82;font-size:12px}.stats{margin:-30px 10px 0;position:relative}.four{grid-template-columns:repeat(4,1fr)}.four .stat-value{font-size:21px}.app-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.app-icon{text-decoration:none}.today{display:flex;align-items:center;justify-content:space-between}.today p{margin:7px 0 0}.today a{color:var(--brand);text-decoration:none;font-size:13px}</style>
